// This is a mock implementation of the Contentful API
// In a real application, you would use the Contentful SDK to fetch data

interface Movie {
  id: string
  title: string
  description: string
  posterUrl: string
  bannerUrl: string
  videoUrl: string
  releaseYear: number
  duration: string
  genres: string[]
  cast: { name: string; character: string; imageUrl: string }[]
  director: string
  language?: string
}

interface Category {
  id: string
  name: string
  movies: Movie[]
}

interface ContentfulData {
  categories: Category[]
}

// Mock data for development
const mockMovies: Movie[] = [
  {
    id: "1",
    title: "The Matrix",
    description:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    posterUrl: "/images/posters/matrix.jpg",
    bannerUrl: "/images/banners/matrix.jpg",
    videoUrl: "https://www.youtube.com/embed/vKQi3bBA1y8",
    releaseYear: 1999,
    duration: "2h 16m",
    genres: ["Action", "Sci-Fi"],
    cast: [
      { name: "Keanu Reeves", character: "Neo", imageUrl: "https://m.media-amazon.com/images/M/MV5BNjUxNDcwMTg4Ml5BMl5BanBnXkFtZTcwNjU4NDYyOA@@._V1_UY100_CR15,0,100,100_AL_.jpg" },
      { name: "Laurence Fishburne", character: "Morpheus", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTc0NjczNDc1MV5BMl5BanBnXkFtZTYwMDU0Mjg1._V1_UX100_CR0,0,100,100_AL_.jpg" },
      { name: "Carrie-Anne Moss", character: "Trinity", imageUrl: "https://m.media-amazon.com/images/M/MV5BMjE2MDQxNjgwM15BMl5BanBnXkFtZTcwNjY5NjA2Mg@@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Hugo Weaving", character: "Agent Smith", imageUrl: "https://m.media-amazon.com/images/M/MV5BMjAxMzAyNDQyM15BMl5BanBnXkFtZTcwOTc5NDIwOQ@@._V1_UY100_CR16,0,100,100_AL_.jpg" },
    ],
    director: "Lana Wachowski, Lilly Wachowski",
  },
  {
    id: "2",
    title: "Inception",
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    posterUrl: "/images/posters/inception.jpg",
    bannerUrl: "/images/banners/inception.jpg",
    videoUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
    releaseYear: 2010,
    duration: "2h 28m",
    genres: ["Action", "Adventure", "Sci-Fi"],
    cast: [
      { name: "Leonardo DiCaprio", character: "Cobb", imageUrl: "https://m.media-amazon.com/images/M/MV5BMjI0MTg3MzI0M15BMl5BanBnXkFtZTcwMzQyODU2Mw@@._V1_UY100_CR15,0,100,100_AL_.jpg" },
      { name: "Joseph Gordon-Levitt", character: "Arthur", imageUrl: "https://m.media-amazon.com/images/M/MV5BZTk5ZGQ0OGQtYWYwMy00ZTE1LWE0ZjgtNDcyMGQ0NGY5YjI4XkEyXkFqcGdeQXVyMjQwMDg0Ng@@._V1_UY100_CR16,0,100,100_AL_.jpg" },
      { name: "Ellen Page", character: "Ariadne", imageUrl: "https://m.media-amazon.com/images/M/MV5BOTM4MzE0OTQyOV5BMl5BanBnXkFtZTgwOTM4MjI2OTE@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Tom Hardy", character: "Eames", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTQ3ODEyNjA4Nl5BMl5BanBnXkFtZTgwMTE4ODMyMjE@._V1_UY100_CR14,0,100,100_AL_.jpg" },
    ],
    director: "Christopher Nolan",
  },
  {
    id: "3",
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    posterUrl: "/images/posters/interstellar.jpg",
    bannerUrl: "/images/banners/interstellar.jpg",
    videoUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
    releaseYear: 2014,
    duration: "2h 49m",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    cast: [
      { name: "Matthew McConaughey", character: "Cooper", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTg0MDc3ODUwOV5BMl5BanBnXkFtZTcwMTk2NjY4Nw@@._V1_UY100_CR14,0,100,100_AL_.jpg" },
      { name: "Anne Hathaway", character: "Brand", imageUrl: "https://m.media-amazon.com/images/M/MV5BNjQ5MDl5ZWItY2EzOC00NWU2LTlhOGYtNGEzYzIzMDgxODljXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UY100_CR39,0,100,100_AL_.jpg" },
      { name: "Jessica Chastain", character: "Murph", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTU1MDM5NjczOF5BMl5BanBnXkFtZTcwOTY2MDE4OA@@._V1_UY100_CR13,0,100,100_AL_.jpg" },
      { name: "Michael Caine", character: "Professor Brand", imageUrl: "https://m.media-amazon.com/images/M/MV5BMjAwNzIwNTQ4Ml5BMl5BanBnXkFtZTYwMzE1MTUz._V1_UY100_CR14,0,100,100_AL_.jpg" },
    ],
    director: "Christopher Nolan",
  },
  {
    id: "4",
    title: "The Dark Knight",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    posterUrl: "/images/posters/dark-knight.jpg",
    bannerUrl: "https://images.hdqwalls.com/wallpapers/batman-the-dark-knight-4k-dp.jpg",
    videoUrl: "https://www.youtube.com/embed/EXeTwQWrcwY",
    releaseYear: 2008,
    duration: "2h 32m",
    genres: ["Action", "Crime", "Drama"],
    cast: [
      { name: "Christian Bale", character: "Bruce Wayne", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTkxMzk4MjQ4MF5BMl5BanBnXkFtZTcwMzExODQxOA@@._V1_UY100_CR16,0,100,100_AL_.jpg" },
      { name: "Heath Ledger", character: "Joker", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTI2NTY0NzA4MF5BMl5BanBnXkFtZTYwMjE1MDE0._V1_UX100_CR0,0,100,100_AL_.jpg" },
      { name: "Aaron Eckhart", character: "Harvey Dent", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTc4MTAyNzMzNF5BMl5BanBnXkFtZTcwMzQ5MzQzMw@@._V1_UY100_CR22,0,100,100_AL_.jpg" },
      { name: "Michael Caine", character: "Alfred", imageUrl: "https://m.media-amazon.com/images/M/MV5BMjAwNzIwNTQ4Ml5BMl5BanBnXkFtZTYwMzE1MTUz._V1_UY100_CR14,0,100,100_AL_.jpg" },
    ],
    director: "Christopher Nolan",
  },
  // Indian Movies - Hindi (Bollywood)
  {
    id: "5",
    title: "3 Idiots",
    description: "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them 'idiots'.",
    posterUrl: "/images/posters/3-idiots.jpg",
    bannerUrl: "https://stat5.bollywoodhungama.in/wp-content/uploads/2016/03/3-Idiots-2.jpg",
    videoUrl: "https://www.youtube.com/embed/xvszmNXdM4w",
    releaseYear: 2009,
    duration: "2h 50m",
    genres: ["Comedy", "Drama"],
    language: "Hindi",
    cast: [
      { name: "Aamir Khan", character: "Rancho", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMTY2OTgwNA@@._V1_UY100_CR13,0,100,100_AL_.jpg" },
      { name: "Madhavan", character: "Farhan", imageUrl: "https://m.media-amazon.com/images/M/MV5BNDgwMzNjMTctZWMxYy00MjQ5LWE5M2EtYzdkMTVmN2VjZTQwXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UY100_CR49,0,100,100_AL_.jpg" },
      { name: "Sharman Joshi", character: "Raju", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTgwMjU0NTA2MF5BMl5BanBnXkFtZTcwNjI5ODY0NA@@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Kareena Kapoor", character: "Pia", imageUrl: "https://m.media-amazon.com/images/M/MV5BZWFmNWNhMzgtZjYxOC00NmQzLTk3NTYtMDc0ODkyNzE4ZTNkXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR40,0,100,100_AL_.jpg" },
    ],
    director: "Rajkumar Hirani",
  },
  {
    id: "6",
    title: "Lagaan",
    description: "In 1893, during the British Raj, a farmer from a small village leads his villagers to challenge British officers to a game of cricket, to avoid paying higher taxes.",
    posterUrl: "/images/posters/lagaan.jpg",
    bannerUrl: "https://www.hindustantimes.com/rf/image_size_1200x900/HT/p2/2020/06/15/Pictures/_6a9ed6f0-aef2-11ea-9c71-6937dcad8e40.jpg",
    videoUrl: "https://www.youtube.com/embed/oSIGQ0YkBxA",
    releaseYear: 2001,
    duration: "3h 44m",
    genres: ["Drama", "Sports", "Historical"],
    language: "Hindi",
    cast: [
      { name: "Aamir Khan", character: "Bhuvan", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMTY2OTgwNA@@._V1_UY100_CR13,0,100,100_AL_.jpg" },
      { name: "Gracy Singh", character: "Gauri", imageUrl: "https://m.media-amazon.com/images/M/MV5BNDIzMTk4NDMtMmI5My00MWY4LTk3MzktOTMwYzRmZGM1N2ZlXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR40,0,100,100_AL_.jpg" },
      { name: "Rachel Shelley", character: "Elizabeth", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTYxNzExNjE5OV5BMl5BanBnXkFtZTcwMjkxNzYxMQ@@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Paul Blackthorne", character: "Captain Russell", imageUrl: "https://m.media-amazon.com/images/M/MV5BMjE2NDEwMzM4OF5BMl5BanBnXkFtZTcwMjI2MTgxMw@@._V1_UY100_CR25,0,100,100_AL_.jpg" },
    ],
    director: "Ashutosh Gowariker",
  },
  {
    id: "7",
    title: "Dilwale Dulhania Le Jayenge",
    description: "A young man and woman fall in love on a European holiday and are separated when they return home. When the woman's family arranges her marriage, her lover returns to win her back.",
    posterUrl: "/images/posters/ddlj.jpg",
    bannerUrl: "https://www.yashrajfilms.com/images/default-source/movies/dilwale-dulhania-le-jayenge/dilwale-dulhania-le-jayenge-about-movie.jpg",
    videoUrl: "https://www.youtube.com/embed/cmax1C1p660",
    releaseYear: 1995,
    duration: "3h 9m",
    genres: ["Romance", "Drama", "Comedy"],
    language: "Hindi",
    cast: [
      { name: "Shah Rukh Khan", character: "Raj Malhotra", imageUrl: "https://m.media-amazon.com/images/M/MV5BZDk1ZmU0NGYtMzQ2Yi00N2NjLTkyNWEtZWE2NTU4NTJiZGUzXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR38,0,100,100_AL_.jpg" },
      { name: "Kajol", character: "Simran Singh", imageUrl: "https://m.media-amazon.com/images/M/MV5BMjI3ODkwNTQxN15BMl5BanBnXkFtZTgwMTk2ODE4MzE@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Amrish Puri", character: "Baldev Singh", imageUrl: "https://m.media-amazon.com/images/M/MV5BNDhkMjU0OTAtZWYzYi00M2U2LThhZGMtNzdlNDQ0NmRkNDlmXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR40,0,100,100_AL_.jpg" },
      { name: "Farida Jalal", character: "Lajwanti Singh", imageUrl: "https://m.media-amazon.com/images/M/MV5BNzZiODZjMjktYTM3NS00MDQzLTliNzEtMmRkOWI2Y2VlNzIzXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR38,0,100,100_AL_.jpg" },
    ],
    director: "Aditya Chopra",
  },
  // Tamil Cinema
  {
    id: "8",
    title: "Vikram",
    description: "A special agent investigates a murder committed by a masked group of serial killers. However, a tangled maze of clues soon leads him to the drug kingpin of Chennai.",
    posterUrl: "/images/posters/vikram.jpg",
    bannerUrl: "https://static.toiimg.com/photo/msid-92061476/92061476.jpg",
    videoUrl: "https://www.youtube.com/embed/OKBMCL-frPU",
    releaseYear: 2022,
    duration: "2h 53m",
    genres: ["Action", "Thriller", "Crime"],
    language: "Tamil",
    cast: [
      { name: "Kamal Haasan", character: "Arun Kumar Vikram", imageUrl: "https://m.media-amazon.com/images/M/MV5BNDExMzIzNjk3Nl5BMl5BanBnXkFtZTcwOTE4NDU5OA@@._V1_UY100_CR29,0,100,100_AL_.jpg" },
      { name: "Vijay Sethupathi", character: "Santhanam", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTEwNzE4MjktMTQzMC00NGEwLTk4NTAtNmJmNDQzMjU1OWYxXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR39,0,100,100_AL_.jpg" },
      { name: "Fahadh Faasil", character: "Amar", imageUrl: "https://m.media-amazon.com/images/M/MV5BYmNhN2EyNzQtOGI5MC00NDM2LThhNzEtZGQwZWVkNGI1MjEyXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Suriya", character: "Rolex", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTgwNzA5MDcxOF5BMl5BanBnXkFtZTgwNTU5OTk5NDE@._V1_UY100_CR15,0,100,100_AL_.jpg" },
    ],
    director: "Lokesh Kanagaraj",
  },
  {
    id: "9",
    title: "Ponniyin Selvan: I",
    description: "Vandiyathevan sets out to cross the Chola land to deliver a message from the Crown Prince Aditha Karikalan. Kundavai attempts to establish political peace as vassals and petty chieftains plot against the throne.",
    posterUrl: "/images/posters/ponniyin-selvan.jpg",
    bannerUrl: "https://c.ndtvimg.com/2022-09/vqnbr8eo_ponniyin-selvan-i-poster_625x300_21_September_22.jpg",
    videoUrl: "https://www.youtube.com/embed/D4qAQYlgZQs",
    releaseYear: 2022,
    duration: "2h 47m",
    genres: ["Historical", "Action", "Drama"],
    language: "Tamil",
    cast: [
      { name: "Vikram", character: "Aditha Karikalan", imageUrl: "https://m.media-amazon.com/images/M/MV5BOTkyMTYwOTYzNl5BMl5BanBnXkFtZTcwNTM2MzU5Ng@@._V1_UY100_CR13,0,100,100_AL_.jpg" },
      { name: "Aishwarya Rai Bachchan", character: "Nandini", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTUzNzA5ODA5MF5BMl5BanBnXkFtZTcwNDQ1NDI5OQ@@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Jayam Ravi", character: "Arulmozhi Varman", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTc0MzYxMDk5NF5BMl5BanBnXkFtZTgwNjY3NjE4NzE@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Karthi", character: "Vallavaraiyan Vandiyadevan", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTc5NzEwNzAwOF5BMl5BanBnXkFtZTgwNjkxODQxNzE@._V1_UY100_CR25,0,100,100_AL_.jpg" },
    ],
    director: "Mani Ratnam",
  },
  // Telugu Cinema
  {
    id: "10",
    title: "Baahubali: The Beginning",
    description: "In ancient India, an adventurous and daring man becomes involved in a decades-old feud between warring cousins.",
    posterUrl: "/images/posters/baahubali.jpg",
    bannerUrl: "https://static.toiimg.com/photo/msid-48154608/48154608.jpg",
    videoUrl: "https://www.youtube.com/embed/sOEg_YZQsTI",
    releaseYear: 2015,
    duration: "2h 38m",
    genres: ["Action", "Drama", "Fantasy"],
    language: "Telugu",
    cast: [
      { name: "Prabhas", character: "Amarendra Baahubali/Shivudu", imageUrl: "https://m.media-amazon.com/images/M/MV5BMGRiMDFjYjMtNjQwMy00Zjc3LWI5ZGUtMTEwZTJmZWU4NGQ2XkEyXkFqcGdeQXVyMjYwMDk5NjE@._V1_UY100_CR81,0,100,100_AL_.jpg" },
      { name: "Rana Daggubati", character: "Bhallaladeva", imageUrl: "https://m.media-amazon.com/images/M/MV5BNGZiMDMzOWQtODU5ZS00ZmYxLWIzNWUtNWEwMmVlODNiNzYxXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR11,0,100,100_AL_.jpg" },
      { name: "Anushka Shetty", character: "Devasena", imageUrl: "https://m.media-amazon.com/images/M/MV5BMjZlZjQ2ZmYtZGFkMi00Y2I1LTlmMDQtMzM1NDBlNTIzZjQ2XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR14,0,100,100_AL_.jpg" },
      { name: "Tamannaah", character: "Avantika", imageUrl: "https://m.media-amazon.com/images/M/MV5BODE5YzdhZjYtZDlkMi00ZTQxLTgyYTktOGU1NGU2MTYwYjkxXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR25,0,100,100_AL_.jpg" },
    ],
    director: "S.S. Rajamouli",
  },
  {
    id: "11",
    title: "RRR",
    description: "A fictional story about two Indian revolutionaries, Alluri Sitarama Raju and Komaram Bheem, who fought against the British Raj and the Nizam of Hyderabad respectively.",
    posterUrl: "/images/posters/rrr.jpg",
    bannerUrl: "/images/banners/rrr.jpg",
    videoUrl: "https://www.youtube.com/embed/f_vbAtFSEc0",
    releaseYear: 2022,
    duration: "3h 7m",
    genres: ["Action", "Drama", "Historical"],
    language: "Telugu",
    cast: [
      { name: "Ram Charan", character: "Alluri Sitarama Raju", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTc3ZWI1MDItMjYxYy00ZGJlLThhYjQtMWQzZmY3MWI3ZWVkXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UY100_CR5,0,100,100_AL_.jpg" },
      { name: "N.T. Rama Rao Jr.", character: "Komaram Bheem", imageUrl: "https://m.media-amazon.com/images/M/MV5BOWU2ZDQyM2YtNzNmZC00MDczLThmYTEtMWM1MzgyMjI3MWEwXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UY100_CR12,0,100,100_AL_.jpg" },
      { name: "Alia Bhatt", character: "Sita", imageUrl: "https://m.media-amazon.com/images/M/MV5BYmIxMmMzYmEtYWVjZi00NDZmLThmZTItNDU4ODdlYjgzYzlhXkEyXkFqcGdeQXVyMTUyNjIwMDEw._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Ajay Devgn", character: "Venkata Rama Raju", imageUrl: "https://m.media-amazon.com/images/M/MV5BNGMzYjM0ZmEtOTU1MC00MmE2LWJmYmJhOTJkODZmYjQzXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR39,0,100,100_AL_.jpg" },
    ],
    director: "S.S. Rajamouli",
  },
  // Malayalam Cinema
  {
    id: "12",
    title: "Drishyam",
    description: "A man goes to extreme lengths to save his family from punishment after his daughter commits an unexpected crime.",
    posterUrl: "/images/posters/drishyam.jpg",
    bannerUrl: "https://www.filmibeat.com/img/2021/05/drishyam-1621487291.jpg",
    videoUrl: "https://www.youtube.com/embed/WiHlKl7_UxI",
    releaseYear: 2013,
    duration: "2h 40m",
    genres: ["Thriller", "Drama", "Mystery"],
    language: "Malayalam",
    cast: [
      { name: "Mohanlal", character: "Georgekutty", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTc5OTYzODg1OF5BMl5BanBnXkFtZTgwMDIzODYxMjI@._V1_UY100_CR16,0,100,100_AL_.jpg" },
      { name: "Meena", character: "Rani", imageUrl: "https://m.media-amazon.com/images/M/MV5BMGI4MmY4MzctZjY5NS00NDRiLTgyYjYtZTQ2MmUzZDg3Mjk1XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Ansiba Hassan", character: "Anju", imageUrl: "https://m.media-amazon.com/images/M/MV5BYzQ2YzRjMmQtNDQ5MS00NzMwLTg1ZTktNDc3YmM4MzQ3NDljXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR14,0,100,100_AL_.jpg" },
      { name: "Esther Anil", character: "Anumol", imageUrl: "https://m.media-amazon.com/images/M/MV5BNjUyZmMzZjQtNWYyZS00MjIwLWJkN2QtMWMxNTY5MDgwMzZlXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR25,0,100,100_AL_.jpg" },
    ],
    director: "Jeethu Joseph",
  },

  {
    id: "12",
    title :"rrr",
    description :"...",
    posterUrl :"",
    bannerUrl:"",
    videoUrl:"https://youtu.be/NgBoMJy386M?si=Pjz0Y6bwEfgvzHdT",
    releaseYear:"",
    releaseYear : "",
    duration:"",
    genres:[],
    language:"",
    cast:[],
    director:"",

  },


  {
    id: "13",
    title: "Kumbalangi Nights",
    description: "Four brothers who share a love-hate relationship with each other live in a dysfunctional household where they argue with each other. Their lives change when three of the brothers fall in love.",
    posterUrl: "/images/posters/kumbalangi-nights.jpg",
    bannerUrl: "https://www.filmibeat.com/img/2019/01/kumbalangeenights-1548935755.jpg",
    videoUrl: "https://www.youtube.com/embed/eq0FHsQWrKY",
    releaseYear: 2019,
    duration: "2h 15m",
    genres: ["Drama", "Family", "Romance"],
    language: "Malayalam",
    cast: [
      { name: "Shane Nigam", character: "Bobby", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Soubin Shahir", character: "Saji", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Fahadh Faasil", character: "Shammi", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Sreenath Bhasi", character: "Bonny", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Madhu C. Narayanan",
  },
  // Bengali Cinema
  {
    id: "14",
    title: "Pather Panchali",
    description: "Impoverished priest Harihar Ray, dreaming of a better life for himself and his family, leaves his rural Bengal village in search of work.",
    posterUrl: "/images/posters/pather-panchali.jpg",
    bannerUrl: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8066_p_v8_aa.jpg",
    videoUrl: "https://www.youtube.com/embed/5ELDeHRmvCo",
    releaseYear: 1955,
    duration: "2h 5m",
    genres: ["Drama", "Classic"],
    language: "Bengali",
    cast: [
      { name: "Subir Banerjee", character: "Apu", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Kanu Banerjee", character: "Harihar", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Karuna Banerjee", character: "Sarbajaya", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Uma Dasgupta", character: "Durga", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Satyajit Ray",
  },
  // Kannada Cinema
  {
    id: "15",
    title: "KGF: Chapter 1",
    description: "A rebellious young man from the streets of Mumbai sets out on a mission to fulfill his mother's wish, while fighting against the gold mafia and political powers.",
    posterUrl: "/images/posters/kgf.jpg",
    bannerUrl: "https://cdn.bollywoodmdb.com/movies/largethumb/2018/k-g-f/k-g-f-poster-9.jpg",
    videoUrl: "https://www.youtube.com/embed/qXQsCfOHDEs",
    releaseYear: 2018,
    duration: "2h 36m",
    genres: ["Action", "Drama", "Period"],
    language: "Kannada",
    cast: [
      { name: "Yash", character: "Rocky", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Srinidhi Shetty", character: "Reena", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Ramachandra Raju", character: "Garuda", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Anant Nag", character: "Anand Ingalagi", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Prashanth Neel",
  },
  {
    id: "16",
    title: "Kantara",
    description: "When greed runs rampant and a dispute arises over land protected by a forest deity, the peace once enjoyed by a small community gradually unravels.",
    posterUrl: "/images/posters/kantara.jpg",
    bannerUrl: "/images/banners/kantara.jpg",
    videoUrl: "https://www.youtube.com/embed/MTECjlKUgEE",
    releaseYear: 2022,
    duration: "2h 30m",
    genres: ["Action", "Adventure", "Drama", "Folklore"],
    language: "Kannada",
    cast: [
      { name: "Rishab Shetty", character: "Shiva/Kaadubettu Shiva", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Sapthami Gowda", character: "Leela", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Kishore", character: "Muralidhar", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Achyuth Kumar", character: "Devendra", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Rishab Shetty",
  },
  {
    id: "17",
    title: "Tumbbad",
    description: "A mythological story about a goddess who created the entire universe. The plot revolves around the consequences when humans build a temple for her first-born.",
    posterUrl: "/images/posters/tumbbad.jpg",
    bannerUrl: "https://images.indianexpress.com/2018/10/tumbbad-759.jpg",
    videoUrl: "https://www.youtube.com/embed/sN75MPxgvX8",
    releaseYear: 2018,
    duration: "1h 44m",
    genres: ["Horror", "Fantasy", "Period"],
    language: "Hindi",
    cast: [
      { name: "Sohum Shah", character: "Vinayak Rao", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Jyoti Malshe", character: "Vinayak's Mother", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Anita Date", character: "Vinayak's Wife", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Ronjini Chakraborty", character: "Servant Tulsi", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Rahi Anil Barve",
  },
  {
    id: "18",
    title: "Jaane Tu Ya Jaane Na",
    description: "Jai and Aditi are best friends who realize they're in love after a series of misunderstandings and the interference of their friends.",
    posterUrl: "/images/posters/jaane-tu-ya-jaane-na.jpg",
    bannerUrl: "https://static.toiimg.com/photo/msid-3193951/3193951.jpg",
    videoUrl: "https://www.youtube.com/embed/gKr9jF4tXo4",
    releaseYear: 2008,
    duration: "2h 35m",
    genres: ["Romance", "Comedy", "Drama"],
    language: "Hindi",
    cast: [
      { name: "Imran Khan", character: "Jai Singh Rathore", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Genelia D'Souza", character: "Aditi Mahant", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Naseeruddin Shah", character: "Amar Singh Rathore", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Ratna Pathak Shah", character: "Savitri Rathore", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Abbas Tyrewala",
  },
  {
    id: "19",
    title: "Super Deluxe",
    description: "An unfaithful newly-wed wife, an estranged father, a priest and an angry son suddenly find themselves in the most unexpected predicaments, each poised to experience their destiny, all on one fateful day.",
    posterUrl: "/images/posters/super-deluxe.jpg",
    bannerUrl: "/images/banners/super-deluxe.jpg",
    videoUrl: "https://www.youtube.com/embed/3-Xq_Zz3nPA",
    releaseYear: 2019,
    duration: "2h 56m",
    genres: ["Drama", "Thriller", "Black Comedy"],
    language: "Tamil",
    cast: [
      { name: "Vijay Sethupathi", character: "Shilpa", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTEwNzE4MjktMTQzMC00NGEwLTk4NTAtNmJmNDQzMjU1OWYxXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR39,0,100,100_AL_.jpg" },
      { name: "Fahadh Faasil", character: "Mugil", imageUrl: "https://m.media-amazon.com/images/M/MV5BYmNhN2EyNzQtOGI5MC00NDM2LThhNzEtZGQwZWVkNGI1MjEyXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Samantha Ruth Prabhu", character: "Vaembu", imageUrl: "https://m.media-amazon.com/images/M/MV5BZjJmNGVhZjctYWNiMi00YTVhLWFjNGUtMWY2NDkwZTZlZDc2XkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Ramya Krishnan", character: "Leela", imageUrl: "https://m.media-amazon.com/images/M/MV5BOGI4ZmJhMGEtN2IxZC00ZTYzLWIxNDYtYjQ0MDMyZDQwZDhkXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR25,0,100,100_AL_.jpg" },
    ],
    director: "Thiagarajan Kumararaja",
  },
  {
    id: "20",
    title: "Gangs of Wasseypur",
    description: "A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, and ignites a deadly blood feud spanning three generations.",
    posterUrl: "/images/posters/gangs-of-wasseypur.jpg",
    bannerUrl: "https://www.bollywoodhungama.com/wp-content/uploads/2016/03/429789025.jpg",
    videoUrl: "https://www.youtube.com/embed/j-AkWDkXcMY",
    releaseYear: 2012,
    duration: "5h 20m",
    genres: ["Crime", "Drama", "Action"],
    language: "Hindi",
    cast: [
      { name: "Manoj Bajpayee", character: "Sardar Khan", imageUrl: "https://m.media-amazon.com/images/M/MV5BYzU3ZGYyZGQtODQ0Ni00NjdlLTlmYzYtZTI1NGJlYTQwZTU5XkEyXkFqcGdeQXVyMDkxMzQwNQ@@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Nawazuddin Siddiqui", character: "Faizal Khan", imageUrl: "https://m.media-amazon.com/images/M/MV5BN2ZkMDIxYzQtNzM2MS00Mjc5LTkzNDMtYzBlYjVkMGNlZTRiXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR40,0,100,100_AL_.jpg" },
      { name: "Richa Chadda", character: "Nagma Khatoon", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTg0NjU4ODAxOV5BMl5BanBnXkFtZTgwNDg5MjIyMDE@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Tigmanshu Dhulia", character: "Ramadhir Singh", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTIzNzg1NzQwN15BMl5BanBnXkFtZTcwNTk1MzkzMQ@@._V1_UY100_CR25,0,100,100_AL_.jpg" },
    ],
    director: "Anurag Kashyap",
  },
  {
    id: "21",
    title: "Asuran",
    description: "The youngest son of a poor farmer from an underprivileged caste kills a rich, upper caste landlord. Will the farmer be able to save his son?",
    posterUrl: "/images/posters/asuran.jpg",
    bannerUrl: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/201910/asuran_1-770x433.jpeg",
    videoUrl: "https://www.youtube.com/embed/vOCM9wztBYQ",
    releaseYear: 2019,
    duration: "2h 19m",
    genres: ["Action", "Drama"],
    language: "Tamil",
    cast: [
      { name: "Dhanush", character: "Sivasaami/Chidambaram", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Manju Warrier", character: "Pachaiyamma", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Prakash Raj", character: "Narasimhan", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Pasupathy", character: "Murugesan", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Vetrimaaran",
  },
  {
    id: "22",
    title: "Arjun Reddy",
    description: "A short-tempered house surgeon gets used to drugs and drinks when his girlfriend is forced to marry another person.",
    posterUrl: "/images/posters/arjun-reddy.jpg",
    bannerUrl: "https://www.mirchi9.com/wp-content/uploads/2017/06/Arjun-Reddy-Posters-1.jpg",
    videoUrl: "https://www.youtube.com/embed/aozErj9NqeE",
    releaseYear: 2017,
    duration: "3h 6m",
    genres: ["Romance", "Drama"],
    language: "Telugu",
    cast: [
      { name: "Vijay Deverakonda", character: "Arjun Reddy Deshmukh", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Shalini Pandey", character: "Preethi Shetty", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Rahul Ramakrishna", character: "Shiva", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Jia Sharma", character: "Jia", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Sandeep Reddy Vanga",
  },
  {
    id: "23",
    title: "Mahanati",
    description: "The story of the life of actress Savitri, one of the most prolific actresses of South India.",
    posterUrl: "/images/posters/mahanati.jpg",
    bannerUrl: "https://gumlet.assettype.com/film-companion%2Fimport%2Fwp-content%2Fuploads%2F2018%2F05%2FMahanati-Lead-1.jpg",
    videoUrl: "https://www.youtube.com/embed/PLmBpf7YUzk",
    releaseYear: 2018,
    duration: "2h 57m",
    genres: ["Biography", "Drama"],
    language: "Telugu",
    cast: [
      { name: "Keerthy Suresh", character: "Savitri", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Dulquer Salmaan", character: "Gemini Ganesan", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Samantha Akkineni", character: "Madhuravani", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Vijay Deverakonda", character: "Vijay Anthony", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Nag Ashwin",
  },
  {
    id: "24",
    title: "Thondimuthalum Driksakshiyum",
    description: "Newlywed migrants in north Kerala struggle within the system as a small-time thief plans to steal their family jewels.",
    posterUrl: "/images/posters/thondimuthalum-driksakshiyum.jpg",
    bannerUrl: "https://images.ottplay.com/images/thondimuthalum-driksakshiyum-406.jpg",
    videoUrl: "https://www.youtube.com/embed/65m1EihomEY",
    releaseYear: 2017,
    duration: "2h 12m",
    genres: ["Drama", "Crime", "Thriller"],
    language: "Malayalam",
    cast: [
      { name: "Suraj Venjaramoodu", character: "Prasad", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Nimisha Sajayan", character: "Sreeja", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Fahadh Faasil", character: "Prasad", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Alencier Ley Lopez", character: "SI P.P. Chandran", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Dileesh Pothan",
  },
  {
    id: "25",
    title: "Jallikattu",
    description: "A buffalo escapes from a slaughterhouse in a remote hill town, and in the search that ensues, the violent, dark side of the villagers comes to the fore.",
    posterUrl: "/images/posters/jallikattu.jpg",
    bannerUrl: "https://images.cinemaexpress.com/uploads/user/imagelibrary/2019/10/8/original/Jallikattu.jpg",
    videoUrl: "https://www.youtube.com/embed/JC4DrlJW7Mk",
    releaseYear: 2019,
    duration: "1h 31m",
    genres: ["Action", "Drama", "Thriller"],
    language: "Malayalam",
    cast: [
      { name: "Antony Varghese", character: "Antony", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Chemban Vinod Jose", character: "Kaalan", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Sabumon Abdusamad", character: "Kuttachan", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Santhy Balachandran", character: "Sophie", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Lijo Jose Pellissery",
  },
  {
    id: "26",
    title: "Aparajito",
    description: "Following his father's death, a boy tries to find a job to support him and his mother but finds the adjustment to adult life difficult.",
    posterUrl: "/images/posters/aparajito.jpg",
    bannerUrl: "https://www.filmcomment.com/wp-content/uploads/sites/2/2015/08/aparajito-banner.jpg",
    videoUrl: "https://www.youtube.com/embed/5ELDeHRmvCo",
    releaseYear: 1956,
    duration: "1h 49m",
    genres: ["Drama", "Classic"],
    language: "Bengali",
    cast: [
      { name: "Smaran Ghosal", character: "Apu (adolescent)", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Kanu Banerjee", character: "Harihar", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Karuna Banerjee", character: "Sarbajaya", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Pinaki Sengupta", character: "Apu (child)", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Satyajit Ray",
  },
  {
    id: "27",
    title: "Charlie",
    description: "Tessa runs away from home to avoid getting married and comes across the works of a free-spirited traveler named Charlie. Fascinated by his lifestyle, she sets out to find him.",
    posterUrl: "/images/posters/charlie.jpg",
    bannerUrl: "https://i.ytimg.com/vi/YkPOVsQTa0o/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/YkPOVsQTa0o",
    releaseYear: 2015,
    duration: "2h 10m",
    genres: ["Drama", "Romance", "Adventure"],
    language: "Malayalam",
    cast: [
      { name: "Dulquer Salmaan", character: "Charlie", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Parvathy Thiruvothu", character: "Tessa", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Aparna Gopinath", character: "Kani", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Nedumudi Venu", character: "Kunjappan", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Martin Prakkat",
  },
  {
    id: "28",
    title: "Jigarthanda",
    description: "When a rookie filmmaker approaches a gangster to make a film on his life, the gangster agrees but with one condition - he will back the film only if the filmmaker makes him the hero.",
    posterUrl: "/images/posters/jigarthanda.jpg",
    bannerUrl: "https://timesofindia.indiatimes.com/photo/37631482.cms",
    videoUrl: "https://www.youtube.com/embed/xU3DrMJRLZQ",
    releaseYear: 2014,
    duration: "2h 50m",
    genres: ["Action", "Crime", "Thriller"],
    language: "Tamil",
    cast: [
      { name: "Siddharth", character: "Karthik Subramani", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Bobby Simha", character: "Assault Sethu", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Lakshmi Menon", character: "Kayal", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Nassar", character: "Producer Muthu", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Karthik Subbaraj",
  },
  {
    id: "29",
    title: "Sairat",
    description: "When two young lovers from different social classes elope, they face the brutal realities of caste discrimination in Indian society.",
    posterUrl: "/images/posters/sairat.jpg",
    bannerUrl: "https://stat5.bollywoodhungama.in/wp-content/uploads/2016/04/Sairat-4.jpg",
    videoUrl: "https://www.youtube.com/embed/wMrMKnoYWwA",
    releaseYear: 2016,
    duration: "2h 54m",
    genres: ["Romance", "Drama"],
    language: "Marathi",
    cast: [
      { name: "Rinku Rajguru", character: "Archana Patil", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Akash Thosar", character: "Prashant Kale", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Tanaji Galgunde", character: "Pradeep Bansode", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Arbaz Shaikh", character: "Salim", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Nagraj Manjule",
  },
  {
    id: "30",
    title: "Premam",
    description: "The story of George and his pursuit of love at different stages in his life, as he falls in love with three different women.",
    posterUrl: "/images/posters/premam.jpg",
    bannerUrl: "https://img.onmanorama.com/content/dam/mm/en/entertainment/movie-reviews/images/2019/4/3/premam.jpg.transform/schema-16x9/image.jpg",
    videoUrl: "https://www.youtube.com/embed/mE3Hz1q1yZ0",
    releaseYear: 2015,
    duration: "2h 36m",
    genres: ["Romance", "Comedy", "Drama"],
    language: "Malayalam",
    cast: [
      { name: "Nivin Pauly", character: "George", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Sai Pallavi", character: "Malar", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Madonna Sebastian", character: "Celine", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Anupama Parameswaran", character: "Mary", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Alphonse Puthren",
  },
  {
    id: "31",
    title: "Vada Chennai",
    description: "A skilled carrom player becomes entangled in the dangerous politics of North Chennai, forcing him to think one step ahead of his opponents to survive.",
    posterUrl: "/images/posters/vada-chennai.jpg",
    bannerUrl: "https://images.deccanchronicle.com/dc-Cover-29kl5ec66g3rbbbj9jrt736sh3-20181017132655.Medi.jpeg",
    videoUrl: "https://www.youtube.com/embed/q5GG5JLXEXg",
    releaseYear: 2018,
    duration: "2h 46m",
    genres: ["Crime", "Action", "Drama"],
    language: "Tamil",
    cast: [
      { name: "Dhanush", character: "Anbu", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Ameer", character: "Rajan", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Andrea Jeremiah", character: "Chandra", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Aishwarya Rajesh", character: "Padma", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Vetrimaaran",
  },
  {
    id: "32",
    title: "Haider",
    description: "A young man returns to Kashmir after his father's disappearance to confront his uncle, whom he suspects of playing a role in his father's fate.",
    posterUrl: "/images/posters/haider.jpg",
    bannerUrl: "https://www.filmibeat.com/img/2014/10/02-haider-review-1.jpg",
    videoUrl: "https://www.youtube.com/embed/ZmN_VSo8DOo",
    releaseYear: 2014,
    duration: "2h 40m",
    genres: ["Action", "Crime", "Drama"],
    language: "Hindi",
    cast: [
      { name: "Shahid Kapoor", character: "Haider Meer", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Tabu", character: "Ghazala Meer", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Kay Kay Menon", character: "Khurram Meer", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Irrfan Khan", character: "Roohdaar", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Vishal Bhardwaj",
  },
  {
    id: "33",
    title: "Rangasthalam",
    description: "A partially deaf village engineer clashes with the local president who exploits the villagers in a rural setting.",
    posterUrl: "/images/posters/rangasthalam.jpg",
    bannerUrl: "https://www.25cineframes.com/images/gallery/2018/03/rangasthalam-telugu-movie-photos-pictures-stills/Rangasthalam-Telugu-Movie-Photos-Pictures-Stills-64.jpg",
    videoUrl: "https://www.youtube.com/embed/sueMmTm-M4Y",
    releaseYear: 2018,
    duration: "2h 59m",
    genres: ["Action", "Drama", "Period"],
    language: "Telugu",
    cast: [
      { name: "Ram Charan", character: "Chitti Babu", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Samantha Akkineni", character: "Rama Lakshmi", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Aadhi Pinisetty", character: "Kumar Babu", imageUrl: "/placeholder.svg?height=100&width=100" },
      { name: "Jagapathi Babu", character: "Phanindra Bhupathi", imageUrl: "/placeholder.svg?height=100&width=100" },
    ],
    director: "Sukumar",
  },
  {
    id: "34",
    title: "Andhadhun",
    description: "A piano player pretending to be blind unwittingly becomes entangled in a series of murders.",
    posterUrl: "/images/posters/andhadhun.jpg",
    bannerUrl: "/images/banners/andhadhun.jpg",
    videoUrl: "https://www.youtube.com/embed/2iVYI99VGaw",
    releaseYear: 2018,
    duration: "2h 19m",
    genres: ["Thriller", "Crime", "Mystery"],
    language: "Hindi",
    cast: [
      { name: "Ayushmann Khurrana", character: "Akash", imageUrl: "https://m.media-amazon.com/images/M/MV5BNzM2YjA3MzYtZWQwMC00YTNiLWIzMGUtNDI4N2Y1MzU2YjY1XkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UY100_CR40,0,100,100_AL_.jpg" },
      { name: "Tabu", character: "Simi", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTU1NDM2MjkwM15BMl5BanBnXkFtZTcwODc2MjU1MQ@@._V1_UX100_CR0,0,100,100_AL_.jpg" },
      { name: "Radhika Apte", character: "Sophie", imageUrl: "https://m.media-amazon.com/images/M/MV5BN2VmZDM2YWYtOGNhYS00ZGQ2LTk5NzUtNDI4Y2IwZmMtNTllXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_UY100_CR25,0,100,100_AL_.jpg" },
      { name: "Anil Dhawan", character: "Pramod Sinha", imageUrl: "https://m.media-amazon.com/images/M/MV5BMTM5NjIwMzU1NF5BMl5BanBnXkFtZTcwNzE2Mjg3NA@@._V1_UY100_CR25,0,100,100_AL_.jpg" },
    ],
    director: "Sriram Raghavan",
  },
]

const mockCategories: Category[] = [
  {
    id: "trending",
    name: "Trending Now",
    movies: [mockMovies[0], mockMovies[1], mockMovies[2], mockMovies[10], mockMovies[15], mockMovies[19], mockMovies[33]],
  },
  {
    id: "action",
    name: "Action Movies",
    movies: [mockMovies[0], mockMovies[3], mockMovies[7], mockMovies[9], mockMovies[10], mockMovies[15], mockMovies[27], mockMovies[30], mockMovies[32]],
  },
  {
    id: "scifi",
    name: "Sci-Fi Adventures",
    movies: [mockMovies[0], mockMovies[1], mockMovies[2]],
  },
  {
    id: "drama",
    name: "Drama",
    movies: [mockMovies[2], mockMovies[3], mockMovies[4], mockMovies[5], mockMovies[8], mockMovies[12], mockMovies[13], mockMovies[20], mockMovies[22], mockMovies[28]],
  },
  {
    id: "bollywood",
    name: "Hindi Cinema",
    movies: [mockMovies[4], mockMovies[5], mockMovies[6], mockMovies[17], mockMovies[18], mockMovies[19], mockMovies[31], mockMovies[33]],
  },
  {
    id: "tamil",
    name: "Tamil Cinema",
    movies: [mockMovies[7], mockMovies[8], mockMovies[18], mockMovies[20], mockMovies[27], mockMovies[30]],
  },
  {
    id: "telugu",
    name: "Telugu Cinema",
    movies: [mockMovies[9], mockMovies[10], mockMovies[21], mockMovies[22], mockMovies[32]],
  },
  {
    id: "malayalam",
    name: "Malayalam Cinema",
    movies: [mockMovies[11], mockMovies[12], mockMovies[23], mockMovies[24], mockMovies[26], mockMovies[29]],
  },
  {
    id: "bengali",
    name: "Bengali Cinema",
    movies: [mockMovies[13], mockMovies[25]],
  },
  {
    id: "kannada",
    name: "Kannada Cinema",
    movies: [mockMovies[14], mockMovies[15]],
  },
  {
    id: "regional",
    name: "Regional Cinema",
    movies: [mockMovies[13], mockMovies[14], mockMovies[25], mockMovies[28]],
  },
  {
    id: "thriller",
    name: "Thriller Movies",
    movies: [mockMovies[7], mockMovies[11], mockMovies[18], mockMovies[23], mockMovies[24], mockMovies[33]],
  },
  {
    id: "romance",
    name: "Romance",
    movies: [mockMovies[6], mockMovies[18], mockMovies[21], mockMovies[26], mockMovies[28], mockMovies[29]],
  },
]

export function fetchContentfulData(): ContentfulData {
  // In a real application, you would fetch this data from Contentful
  return {
    categories: mockCategories,
  }
}

export function fetchMovieById(id: string): Movie | null {
  // In a real application, you would fetch this data from Contentful
  const movie = mockMovies.find((movie) => movie.id === id)
  return movie || null
}

export function fetchMoviesByLanguage(language: string): Movie[] {
  // In a real application, you would fetch this data from Contentful
  return mockMovies.filter((movie) => movie.language === language)
}

export function fetchMoviesByGenre(genre: string): Movie[] {
  // In a real application, you would fetch this data from Contentful
  return mockMovies.filter((movie) => movie.genres.includes(genre))
}

